// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvN1oIwzEVEK-4k0Xg4VZ12vd_GNFNeGU',
    appId: '1:845034754213:web:5e7acb4b2a97e6da31bd4c',
    messagingSenderId: '845034754213',
    projectId: 'etore-c3e79',
    authDomain: 'etore-c3e79.firebaseapp.com',
    storageBucket: 'etore-c3e79.appspot.com',
    measurementId: 'G-W569YCS1J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17RxjkqRB0MoiF0fCtaTZPxBc-a1xTJE',
    appId: '1:845034754213:android:48dc5afb2cc8975e31bd4c',
    messagingSenderId: '845034754213',
    projectId: 'etore-c3e79',
    storageBucket: 'etore-c3e79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1lek-yvwbZ6eFDBqveJYxYDxokptORuo',
    appId: '1:845034754213:ios:3662b5005759787531bd4c',
    messagingSenderId: '845034754213',
    projectId: 'etore-c3e79',
    storageBucket: 'etore-c3e79.appspot.com',
    iosClientId: '845034754213-i28jj79dq3s1o3i6f7tl28hqrf5g9vfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
